In [1]:
import pandas as pd

## Загрузка данных

In [2]:
data = pd.read_csv('data.txt', sep=';')

In [3]:
data[:5]

DATA_TYPE  POLICY_ID  POLICY_BEGIN_MONTH  POLICY_END_MONTH  \
0     TRAIN          1                   1                 1   
1     TRAIN          2                   1                 1   
2     TRAIN          3                   1                 1   
3     TRAIN          4                   1                 1   
4     TRAIN          5                   1                 1   

   POLICY_IS_RENEWED  POLICY_SALES_CHANNEL  POLICY_SALES_CHANNEL_GROUP  \
0                  1                    39                           1   
1                  1                    50                           5   
2                  1                    52                           6   
3                  1                    50                           5   
4                  0                    52                           6   

     POLICY_BRANCH  POLICY_MIN_AGE  POLICY_MIN_DRIVING_EXPERIENCE  ...  \
0           Москва              51                             12  ...   
1           Москва              35                              7  ...   
2           Москва              41                              6  ...   
3           Москва              36                             12  ...   
4  Санкт-Петербург              42                              5  ...   

  POLICY_PRV_CLM_GLT_N CLIENT_HAS_DAGO  CLIENT_HAS_OSAGO  POLICY_COURT_SIGN  \
0                    N               1                 0                  0   
1                    0               1                 1                  0   
2                   1L               0                 0                  0   
3                    0               1                 1                  0   
4                    N               0                 0                  0   

   CLAIM_AVG_ACC_ST_PRD POLICY_HAS_COMPLAINTS POLICY_YEARS_RENEWED_N  \
0                   0.0                     0                      0   
1                   0.0                     0                      4   
2                   0.0                     0                      1   
3                   0.0                     0                      6   
4                   0.0                     0                      0   

  POLICY_DEDUCT_VALUE CLIENT_REGISTRATION_REGION POLICY_PRICE_CHANGE  
0                 0.0                   Тульская               -1.00  
1                 0.0                     Москва               -0.05  
2             12518.0                 Московская               -0.07  
3             15000.0                     Москва                0.05  
4             50000.0              Ленинградская                0.17  

[5 rows x 30 columns]

## Работа с признаками

In [4]:
data.columns

Index(['DATA_TYPE', 'POLICY_ID', 'POLICY_BEGIN_MONTH', 'POLICY_END_MONTH',
       'POLICY_IS_RENEWED', 'POLICY_SALES_CHANNEL',
       'POLICY_SALES_CHANNEL_GROUP', 'POLICY_BRANCH', 'POLICY_MIN_AGE',
       'POLICY_MIN_DRIVING_EXPERIENCE', 'VEHICLE_MAKE', 'VEHICLE_MODEL',
       'VEHICLE_ENGINE_POWER', 'VEHICLE_IN_CREDIT', 'VEHICLE_SUM_INSURED',
       'POLICY_INTERMEDIARY', 'INSURER_GENDER', 'POLICY_CLM_N',
       'POLICY_CLM_GLT_N', 'POLICY_PRV_CLM_N', 'POLICY_PRV_CLM_GLT_N',
       'CLIENT_HAS_DAGO', 'CLIENT_HAS_OSAGO', 'POLICY_COURT_SIGN',
       'CLAIM_AVG_ACC_ST_PRD', 'POLICY_HAS_COMPLAINTS',
       'POLICY_YEARS_RENEWED_N', 'POLICY_DEDUCT_VALUE',
       'CLIENT_REGISTRATION_REGION', 'POLICY_PRICE_CHANGE'],
      dtype='object')

In [5]:
for column in data.columns:
    print('column is: ', column, 'type: ', data[column].dtypes)
    print(data[column].unique())

column is:  DATA_TYPE type:  object
['TRAIN' 'TEST ']
column is:  POLICY_ID type:  int64
[    1     2     3 ... 96603 96604 96605]
column is:  POLICY_BEGIN_MONTH type:  int64
[ 1  2 11 12  3  8  9  4 10  7  5  6]
column is:  POLICY_END_MONTH type:  int64
[ 1  2 11 12  3  8  9  4 10  7  5  6]
column is:  POLICY_IS_RENEWED type:  int64
[1 0]
column is:  POLICY_SALES_CHANNEL type:  int64
[39 50 52  2 10 53 54  1  6 55 17 20 37 23 29 59 15  8 40 41 14 11 62 60
 46  5 22 31 51  3 16 25 27 63 45  4 13 18 26 44 28  7  9 47 49 38 35 12
 57 21 19 43 24 34 30 32 33 42 61 36 48 58 56]
column is:  POLICY_SALES_CHANNEL_GROUP type:  int64
[1 5 6 4 3 8 2 7]
column is:  POLICY_BRANCH type:  object
['Москва' 'Санкт-Петербург']
column is:  POLICY_MIN_AGE type:  int64
[51 35 41 36 42 60 48 27 56 38 53 30 39 64 47 61 44 40 49 50 31 32 33 62
 28 46 58 26 63 37 34 25 29 24 65 45 66 54 55 23 52 57 67 43 59 69 78 68
 75 22 18 76 74 80 72 19 73 77 71 20 79 70 21 86 82 81 83 84]
column is:  POLICY_MIN_DRIVING_E

TODO: 

* В колонке VECHICLE_MODEL есть колонка '<пусто>'. Посмотреть что там
* В колонке POLICY_INTERMEDIARY есть колонка 'N'. Посмотреть что там
* POLICY_PRV_CLM_N - 'N'
* POLICY_PRV_CLM_N - 'N'
* POLICY_YEARS_RENEWED_N - 'N'

...

answ: тк все фичи имеющие значение N - невелики по уникальности - можем лейблэнкодить

## Get target variable

In [6]:
y = data['POLICY_IS_RENEWED']

In [7]:
y.dtypes

dtype('int64')

In [8]:
y.unique()

array([1, 0])

In [9]:
one_ind = data['POLICY_IS_RENEWED'] == 1
len(y[one_ind]), len(y) - len(y[one_ind])

(48376, 48229)

In [10]:
train_ind = data['DATA_TYPE'] == 'TRAIN'
len(y[one_ind&train_ind]), len(y[train_ind]) - len(y[one_ind&train_ind])

(48376, 29031)

* Тренировочную выборку можно сбалансировать!

## One hot encoding to categorial features

In [11]:
from sklearn.preprocessing import LabelEncoder

categorial_features = ['POLICY_BRANCH', 'VEHICLE_MAKE', 'VEHICLE_MODEL', 'POLICY_INTERMEDIARY', 'INSURER_GENDER', 'POLICY_CLM_N', 
                       'POLICY_CLM_GLT_N', 'POLICY_PRV_CLM_N', 'POLICY_PRV_CLM_GLT_N', 'POLICY_YEARS_RENEWED_N', 'CLIENT_REGISTRATION_REGION']
numeric_features = list(set(data.columns) - set(categorial_features) - {'DATA_TYPE'} - {'POLICY_IS_RENEWED'})


In [12]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
cat_transform_data = ohe.fit_transform(data[categorial_features]).toarray()
cat_transform_data.shape

(96605, 2167)

## Label encoding for categorial features


In [24]:
from sklearn.preprocessing import LabelEncoder
data_le = pd.DataFrame(data=data[categorial_features],columns=categorial_features)

for column in categorial_features:
    le = LabelEncoder()
    data_le[column] = le.fit_transform(data[column])

## Scale numeric features

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
num_transform_data = scaler.fit_transform(data[numeric_features])
num_transform_data.shape

(96605, 17)

In [14]:
cat_transform_data.shape, num_transform_data.shape

((96605, 2167), (96605, 17))

In [15]:
import numpy as np
transformed_data = np.concatenate((cat_transform_data, num_transform_data), axis=1)
transformed_data.shape

(96605, 2184)

In [16]:
train_indices = data['DATA_TYPE'] == 'TRAIN'
train = transformed_data[train_indices]
train
y_train = y[train_indices]

In [17]:
test_indices = data['DATA_TYPE'] == 'TEST '
test = transformed_data[test_indices]
test
y_test = y[test_indices]

In [18]:
len(test) + len(train) == len(data)

True

## Ridge regression

In [23]:
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import confusion_matrix

ridge = RidgeClassifier()
ridge.fit(train, y_train)
tn, fp, fn, tp = confusion_matrix(y_test, ridge.predict(test)).ravel()


MemoryError: Unable to allocate 1.26 GiB for an array with shape (77407, 2184) and data type float64

In [157]:
tn, fp, fn, tp

(3694, 15504, 0, 0)

In [170]:
from sklearn.model_selection import cross_validate

scores = cross_validate(ridge, train, y_train, cv=5,
                         scoring=('accuracy'),
                         return_train_score=True)

scores

{'fit_time': array([9.33801222, 8.02453136, 8.29879618, 7.69241834, 8.08237338]),
 'score_time': array([0.08676839, 0.06881499, 0.06582427, 0.0668211 , 0.06682253]),
 'test_score': array([0.66440612, 0.6707577 , 0.66778632, 0.67431045, 0.66759253]),
 'train_score': array([0.68837607, 0.68748183, 0.68854762, 0.68727191, 0.68940348])}

In [172]:
scores['test_score'].mean()

0.6689706244784486

In [173]:
import pickle
# now you can save it to a file
with open('clf.pkl', 'wb') as f:
    pickle.dump(ridge, f)

# and later you can load it
with open('clf.pkl', 'rb') as f:
    clf = pickle.load(f)